### ISSUE TITLE
No Sql file =((

### ISSUE THREAD

**Issue by TranHuyHoang2001** [SanchaiAhilan/Supermarket-Billing-system#1]
extract zip file don't have sql file bro! i think i need sql file to run

**Comment by SanchaiAhilan** [comment]
I didn't use SQL to create tables, the whole database is created using the NetBeans inbuilt tool for creating tables. Unfortunately, those tables are not created within the project directory itself, hence I couldn't include them here. You may want to create those tables yourself.

You have to import a jar file to make use of it. All the jar files (libraries) are found within the dist folder. 

You can refer this video to create your own tables. This project is based on the project that is on this video.
https://www.youtube.com/watch?v=ByLOrDhn7B0

**Comment by TranHuyHoang2001** [comment]
Thanks you very much bro !

**Comment by toukirkhan** [comment]
How to the admin or seller panel?

**Comment by SanchaiAhilan** [comment]
Please refer to the below video for a step by step tutorial.
https://www.youtube.com/watch?v=ByLOrDhn7B0

**Comment by toukirkhan** [comment]
Alrighty!
